<?php

declare(strict_types=1);

namespace Mammatus\Groups;

use InvalidArgumentException;
use Mammatus\DevApp\Groups\LifeIsLife;
use Mammatus\Groups\Attributes\Group;
use Mammatus\Groups\Contracts\LifeCycleHandler;
use Mammatus\LifeCycleEvents\Shutdown;
use Psr\Container\ContainerInterface;
use WyriHaximus\Broadcast\Contracts\AsyncListener;

/**
 * This class is generated by mammatus/groups, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
final class Groups implements AsyncListener
{
    /** @var array<string, array<int, LifeCycleHandler>> */
    private array $groups = [];

    /** @phpstan-ignore ergebnis.noParameterWithContainerTypeDeclaration */
    public function __construct(
        private readonly ContainerInterface $container,
    ) {
    }

    public function boot(string $group): void
    {
        $this->groups[$group] = [];
        foreach ($this->lifeCycleHandlers($group) as $handler) {
            /** @phpstan-ignore assign.propertyType */
            $this->groups[$group][] = $this->container->get($handler);
        }

        foreach ($this->groups[$group] as $handler) {
            /** @phpstan-ignore method.nonObject */
            $handler->start();
        }
    }

    public function shutdown(Shutdown $shutdown): void
    {
        foreach ($this->groups as $group) {
            foreach ($group as $handler) {
                $handler->stop();
            }
        }
    }

    /**
     * @return iterable<string, Group>
     *
     * @api
     */
    final public static function groups(): iterable
    {
        yield 'music' => new Group(
            Type::Daemon,
            'music',
        );

        yield from [];
    }

    /** @return list<class-string<LifeCycleHandler>> */
    private function lifeCycleHandlers(string $group): iterable
    {
        return match ($group) {
            'music' => [
                LifeIsLife::class,
            ],
            default => throw new InvalidArgumentException('No life cycle handlers found for group ' . $group),
        };
    }
}
