<?php declare(strict_types=1);

namespace Mammatus\Groups;

/**
 * This class is generated by mammatus/groups, do not edit manually.
 * Or do, I'm not your parent, they will be overwritten next composer install/update ¯\_(ツ)_/¯.
 */
final class Groups implements \WyriHaximus\Broadcast\Contracts\AsyncListener
{
    /** @var array<string, array<int, \Mammatus\Groups\Contracts\LifeCycleHandler>> */
    private array $groups = [];

    /** @phpstan-ignore ergebnis.noParameterWithContainerTypeDeclaration */
    public function __construct(
        private readonly \Psr\Container\ContainerInterface $container,
    ) {
    }

    public function boot(string $group): void
    {
        $this->groups[$group] = [];
        foreach ($this->lifeCycleHandlers($group) as $handler) {
            /** @phpstan-ignore assign.propertyType */
            $this->groups[$group][] = $this->container->get($handler);
        }

        foreach ($this->groups[$group] as $handler) {
            /** @phpstan-ignore method.nonObject */
            $handler->start();
        }
    }

    public function shutdown(\Mammatus\LifeCycleEvents\Shutdown $shutdown): void
    {
        foreach ($this->groups as $group) {
            foreach ($group as $handler) {
                $handler->stop();
            }
        }
    }

    /**
     * @api
     * @return iterable<string, \Mammatus\Groups\Attributes\Group>
     */
    final public static function groups(): iterable
    {
        yield 'app' => new \Mammatus\Groups\Attributes\Group(
            \Mammatus\Groups\Type::Normal,
            'app',
        );
        yield 'music' => new \Mammatus\Groups\Attributes\Group(
            \Mammatus\Groups\Type::Daemon,
            'music',
        );
        yield from [];
    }

    /**
     * @param string $group
     * @return list<string>
     */
    public static function lookUpNormalFor(string $group): array
    {
        return match ($group) {
            'app' => [
                'app',
                ],
            'music' => [
                'app',
                ],
            default => throw new \InvalidArgumentException('No group found for ' . $group),
        };
    }

    /**
     * @return list<class-string<\Mammatus\Groups\Contracts\LifeCycleHandler>>
     */
    private function lifeCycleHandlers(string $group): iterable
    {
        return match ($group) {
        'app' => [
            \Mammatus\Groups\Fallback\DealingWIthLife::class,
            ],
            'music' => [
            \Mammatus\DevApp\Groups\LifeIsLife::class,
            ],
            default => throw new \InvalidArgumentException('No life cycle handlers found for group ' . $group),
        };
    }
}
